# Generated by Django 4.2.7 on 2023-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalPortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='future_plans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role_and_contribution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_stack',
            field=models.TextField(null=True),
        ),
    ]
