# Generated by Django 4.2.7 on 2023-11-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalPortfolioApp', '0002_rename_name_project_title_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges_solutions',
            field=models.TextField(null=True),
        ),
    ]
