# Generated by Django 5.0.4 on 2024-04-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalPortfolioApp', '0003_project_challenges_solutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='git_repo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='git_repo_links',
            field=models.ManyToManyField(blank=True, to='PersonalPortfolioApp.gitrepository'),
        ),
    ]
