# Generated by Django 5.0.4 on 2024-04-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalPortfolioApp', '0004_gitrepository_remove_project_git_repo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='name',
            field=models.CharField(default='Untitled Repository', max_length=100),
        ),
    ]
