# Generated by Django 5.0.4 on 2024-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalPortfolioApp', '0005_gitrepository_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitrepository',
            name='name',
            field=models.CharField(default='Git Repository', max_length=100),
        ),
    ]
