# Generated by Django 5.0.4 on 2024-04-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalPortfolioApp', '0007_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='project_images/'),
        ),
    ]
